name = "libpq-fortran"
version = "0.1.0"
license = "MIT License"
author = "Amasaki Shinobu"
maintainer = "amasaki203@gmail.com"
copyright = "Copyright 2023, Amasaki Shinobu"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
link = ['pq']
[install]
library = true
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]
uint-fortran = {git ="https://github.com/ShinobuAmasaki/uint-fortran"}

[[example]]
name = "demo"
main = "demo.f90"
